# Generated by Django 4.2.5 on 2023-09-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.RemoveField(
            model_name="post",
            name="text",
        ),
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
        migrations.AddField(
            model_name="post",
            name="image_eight",
            field=models.ImageField(blank=True, null=True, upload_to="postsimages/"),
        ),
        migrations.AddField(
            model_name="post",
            name="image_five",
            field=models.ImageField(blank=True, null=True, upload_to="postsimages/"),
        ),
        migrations.AddField(
            model_name="post",
            name="image_four",
            field=models.ImageField(blank=True, null=True, upload_to="postsimages/"),
        ),
        migrations.AddField(
            model_name="post",
            name="image_nine",
            field=models.ImageField(blank=True, null=True, upload_to="postsimages/"),
        ),
        migrations.AddField(
            model_name="post",
            name="image_one",
            field=models.ImageField(blank=True, null=True, upload_to="postsimages/"),
        ),
        migrations.AddField(
            model_name="post",
            name="image_seven",
            field=models.ImageField(blank=True, null=True, upload_to="postsimages/"),
        ),
        migrations.AddField(
            model_name="post",
            name="image_six",
            field=models.ImageField(blank=True, null=True, upload_to="postsimages/"),
        ),
        migrations.AddField(
            model_name="post",
            name="image_ten",
            field=models.ImageField(blank=True, null=True, upload_to="postsimages/"),
        ),
        migrations.AddField(
            model_name="post",
            name="image_three",
            field=models.ImageField(blank=True, null=True, upload_to="postsimages/"),
        ),
        migrations.AddField(
            model_name="post",
            name="image_two",
            field=models.ImageField(blank=True, null=True, upload_to="postsimages/"),
        ),
        migrations.AddField(
            model_name="post",
            name="text_eight",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="text_five",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="text_four",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="text_nine",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="text_one",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="text_seven",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="text_six",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="text_ten",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="text_three",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="text_two",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_eight",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_five",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_four",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_nine",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_one",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_seven",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_six",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_ten",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_three",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_two",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
