# Generated by Django 4.2.5 on 2023-10-02 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_comment_post_alter_post_index_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="index_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="blog.index",
            ),
        ),
    ]
