# Generated by Django 4.2.5 on 2023-10-02 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_post_index_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Extra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("sub_title", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="postimages/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TabullarData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(blank=True, max_length=100, null=True)),
                ("col_one", models.TextField(blank=True, null=True)),
                ("col_two", models.TextField(blank=True, null=True)),
                ("col_three", models.TextField(blank=True, null=True)),
                ("col_four", models.TextField(blank=True, null=True)),
                ("col_five", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="index_title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="blog.index",
            ),
        ),
    ]
