# Generated by Django 4.2.5 on 2023-10-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_extra_tabullardata_alter_post_index_title"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TabullarData",
            new_name="TabularData",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="index_title",
            new_name="index",
        ),
        migrations.AddField(
            model_name="extra",
            name="summary_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="summary_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
