# Generated by Django 4.2.5 on 2023-10-02 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_rename_tabullardata_tabulardata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tabulardata",
            name="extra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.extra",
            ),
        ),
        migrations.AddField(
            model_name="tabulardata",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.post",
            ),
        ),
        migrations.AlterField(
            model_name="extra",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="others/"),
        ),
    ]
