# Generated by Django 4.2.5 on 2023-10-02 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_tabulardata_extra_tabulardata_post_alter_extra_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tabulardata",
            name="extra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="table",
                to="blog.extra",
            ),
        ),
        migrations.AlterField(
            model_name="tabulardata",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="table",
                to="blog.post",
            ),
        ),
    ]
