# Generated by Django 4.2.5 on 2023-10-02 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_alter_tabulardata_extra_alter_tabulardata_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_header", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="extra",
            old_name="description",
            new_name="text",
        ),
        migrations.RemoveField(
            model_name="extra",
            name="image",
        ),
        migrations.RemoveField(
            model_name="extra",
            name="sub_title",
        ),
        migrations.RemoveField(
            model_name="extra",
            name="summary_text",
        ),
        migrations.RemoveField(
            model_name="tabulardata",
            name="col_five",
        ),
        migrations.RemoveField(
            model_name="tabulardata",
            name="col_four",
        ),
        migrations.RemoveField(
            model_name="tabulardata",
            name="col_one",
        ),
        migrations.RemoveField(
            model_name="tabulardata",
            name="col_three",
        ),
        migrations.RemoveField(
            model_name="tabulardata",
            name="col_two",
        ),
        migrations.AddField(
            model_name="post",
            name="extra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extras",
                to="blog.extra",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="index",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="blog.index",
            ),
        ),
        migrations.CreateModel(
            name="TableRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_row", models.CharField(max_length=100)),
                (
                    "table_header",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trow",
                        to="blog.tableheader",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tableheader",
            name="tabular_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="theader",
                to="blog.tabulardata",
            ),
        ),
    ]
