# Generated by Django 4.2.5 on 2023-10-02 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_tableheader_rename_description_extra_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="extra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="blog.extra",
            ),
        ),
    ]
