# Generated by Django 4.2.5 on 2023-10-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_alter_post_extra"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(blank=True, max_length=100, null=True)),
                ("col_one", models.CharField(blank=True, max_length=200, null=True)),
                ("col_two", models.CharField(blank=True, max_length=200, null=True)),
                ("col_three", models.CharField(blank=True, max_length=200, null=True)),
                ("col_four", models.CharField(blank=True, max_length=200, null=True)),
                ("col_five", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="tablerow",
            name="table_header",
        ),
        migrations.RemoveField(
            model_name="tabulardata",
            name="extra",
        ),
        migrations.RemoveField(
            model_name="tabulardata",
            name="post",
        ),
        migrations.RenameField(
            model_name="extra",
            old_name="text",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="post",
            name="extra",
        ),
        migrations.AddField(
            model_name="extra",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="others/"),
        ),
        migrations.AddField(
            model_name="extra",
            name="sub_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="extra",
            name="summary_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="TableHeader",
        ),
        migrations.DeleteModel(
            name="TableRow",
        ),
        migrations.DeleteModel(
            name="TabularData",
        ),
    ]
