# Generated by Django 4.2.5 on 2023-10-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_tabledata_remove_tablerow_table_header_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_for",
                    models.CharField(
                        choices=[
                            ("casts", "casts"),
                            ("seasons", "seasons"),
                            ("about", "about"),
                        ],
                        max_length=7,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("summary_text", models.TextField(blank=True, null=True)),
                ("sub_title", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="others/"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Extra",
        ),
        migrations.AddField(
            model_name="tabledata",
            name="content_for",
            field=models.CharField(
                choices=[
                    ("casts", "casts"),
                    ("seasons", "seasons"),
                    ("about", "about"),
                ],
                default="casts",
                max_length=7,
            ),
            preserve_default=False,
        ),
    ]
