# Generated by Django 4.2.5 on 2023-10-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0015_general_delete_extra_tabledata_content_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="tabledata",
            name="related_to",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
