# Generated by Django 4.2.5 on 2023-10-05 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0016_tabledata_related_to"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="index",
            options={"ordering": ["-id"]},
        ),
    ]
