# Generated by Django 4.2.5 on 2023-10-05 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0018_contactme"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactMe",
        ),
    ]
